### PR TITLE
ENG-105 plugin list feature

### PR DESCRIPTION
**Pull request by gidesan**
Currently blocked by ENG-104

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Review by ichalagashvili — APPROVED** [review]
All good

**Pull request closed without merging**
