### PR TITLE
EN-2250 & EN-2251 prepare mock API and redux boilerplate state for marketplaces

### PR DESCRIPTION
**Pull request by otarza**
1. https://jira.entando.org/browse/EN-2250
2. https://jira.entando.org/browse/EN-2251

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by nicpuddu** [comment]
waiting on the tests to be added

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Pull request merged**
