### PR TITLE
EN-2334 Implementing Components List View.

### PR DESCRIPTION
**Pull request by otarza**
Ready to be reviewed.

https://jira.entando.org/browse/EN-2334

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by gidesan** [comment]
Why use `ContainReact` instead of DOM helpers?

**Comment by otarza** [comment]
@gidesan updated, please have a look. 

Thank you.

**Comment by entando-service** [comment]
All is well

**Comment by gidesan** [comment]
Sorry if I wasn't totally clear, but I meant checking DOM attributes and not component props: we should ensure data to show is in the correct DOM place.

**Comment by otarza** [comment]
@gidesan tests updated, hopefully I get it right this time 😀

Please have a look.

**Comment by entando-service** [comment]
All is well

**Pull request merged**
