### PR TITLE
ENG-1100: fix the details link on find template modal

### PR DESCRIPTION
**Pull request by gReis89**
changing the way of building the link to work on different environments

### CODE REVIEW

**Comment by entando-jx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **greis89**

If they are not already assigned, you can assign the PR to them by writing `/assign @greis89` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by gidesan — COMMENTED** [review]
why usage of `routeConverter` wasn't a good fit?

**Comment by gReis89** [comment]
> why usage of `routeConverter` wasn't a good fit?

Simone found this issue with the details link:

```
Also I've found an issue in the link opened when you click on "Details" the opened link should be  something like  "http://quickstart-qe-one.apps.rd.entando.org/app-builder/page-template/view/OotbcHomepage" and NOT this "http://quickstart-qe-one.apps.rd.entando.org/page-template/view/OotbcHomepage".
```

The test environment has an extra `app-builder` route in the URL which we don't have on localhost, for some reason, when using `routeConverter` without the `history.push`, we lose the page context and the link is wrong. So I had to use `location.href` to preserve the `app-builder` or anything else that it may be named.

Please, let me know if there are a better solution for that.

**Review by gidesan — APPROVED** [review]

**Comment by entando-jx** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando/app-builder/pull/843#pullrequestreview-489708247" title="Approved">gidesan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)~~ [gidesan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
