### PR TITLE
EN 1347 category details

### PR DESCRIPTION
**Pull request by mcarta-rt**
ui unit tests missing

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by mcarta-rt** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by fedelocci** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by fedelocci** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
