### PR TITLE
EN6-92 Fix menu height issue

### PR DESCRIPTION
**Pull request by raxkaynan**
The fix is just by overriding the Patternfly style for active menu items in a persistent secondary navbar. It seems that they didn't consider a mix of multi-level menu items and single-level ones as the corresponding style appears to be only suitable for multi-level items.

### CODE REVIEW

**Comment by raxkaynan** [comment]
Retest this please.

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by raxkaynan** [comment]
Retest this please.

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Pull request merged**
